# This is a basic workflow to help you get started with Actions

name: dev-ci-cd

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

     # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: '14.x'
          
      # Install project dependencies
      - name: Install dependencies
        run: npm install
      
      # Check for lint issues
      - name: Run Lint
        run: npm run lint:ci
        
      # Build
      - name: Build
        run: npm run build:prod
        
      # Copy files
      - name: Copy file
        uses: canastro/copy-file-action@master
        with:
          source: "firebase.json"
          target: "dist/firebase.json"
          
      # Upload build artifacts
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          # A file, directory or wildcard pattern that describes what to upload
          name: dist
          path: dist
          if-no-files-found: error
          
  # This workflow contains a single job called "build"
  deploy:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v2.0.8
          with:
            # Destination path
            name: dist
        
        - name: Make envfile
          uses: SpicyPizza/create-envfile@v1
          with:
            envkey_SERVICE_DOMAIN: ${{ secrets.SERVICE_DOMAIN_DEV }}

        - name: Deploy the build
          uses: w9jds/firebase-action@v2.0.0
          with:
            args: deploy --project ${{ secrets.FIREBASE_DEV_APPID }}
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            TARGET: dev
